#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l pmem=14gb
#PBS -l walltime=24:00:00
#PBS -A my-allocation
#PBS -o run_strainid.log.out
#PBS -e run_strainid.log.err

module load gcc
module load samtools
module load anaconda3
source activate mittal

# REPLACE WITH YOUR PATH
WRK=/path/to/2022-Mittal_SAGA/
GENOME=/path/to/sacCer3.fa
STRAINID=/path/to/GenoPipe/StrainID
OUTPUT=$WRK/01_Run_GenoPipe/epitopeid

cd $WRK
[ -d logs ] || mkdir logs
[ -d $OUTPUT ] || mkdir $OUTPUT

cd $STRAINID
bash identify-Strain.sh -i $WRK/data/BAM/ -v $STRAINID/sacCer3_VCF/ -g $GENOME -o $OUTPUT
